### ISSUE TITLE
Build not passing on Android

### ISSUE THREAD

**Issue by JohannesaBrahms** [nekronos/FuseNativeControls#12]
Hi,

We're trying to test the Lib on Android (the iOS build works fine), but can't seem to get the solution to build. We're using this command to build **uno build -tAndroid -DGradle -r --set:SDK.BuildToolsVersion="23.0.3" --set:SDK.CompileVersion="23" --set:SDK.TargetVersion="23"**, and we keep getting these compile-time errors:

..\NativeControls\DatePicker.ScriptClass.uno(110.33): E3104: Uno.Data.Json.JsonReader does not contain a member called 'AsNumber'. Could you be missing a package reference?
..\NativeControls\DatePicker.ScriptClass.uno(111.35): E3104: Uno.Data.Json.JsonReader does not contain a member called 'AsNumber'. Could you be missing a package reference?
..\NativeControls\DatePicker.ScriptClass.uno(112.31): E3104: Uno.Data.Json.JsonReader does not contain a member called 'AsNumber'. Could you be missing a package reference?
..\NativeControls\TimePicker.ScriptClass.uno(84.33): E3104: Uno.Data.Json.JsonReader does not contain a member called 'AsNumber'. Could you be missing a package reference?
..\NativeControls\TimePicker.ScriptClass.uno(85.37): E3104: Uno.Data.Json.JsonReader does not contain a member called 'AsNumber'. Could you be missing a package reference?

Is the Lib missing a dependency on Android?

---
We've already come across some JS-parsing-related runtime issues between iOS and Android, where it seemed we had to marshal ints when passing data from JS, because iOS made and issue of it, whereas Android handled it as expected. They don't seem to work the same under the hood.

**Comment by nekronos** [comment]
What version of `uno` are you using? I cannot reproduce this with latest installer from fusetools.com

**Comment by JohannesaBrahms** [comment]
Uno version 0.46.1 (build 4840) Windows 10 x64 3caace9

Product information
  Product.Commit            3caace9ea21066086fce0a80ea9c682e894b59c5
  Product.Version           0.46.1.4840

EDIT: one of our colleagues has some animation issues with the latest fuse version, so we decided to revert to the last stable version.

**Comment by nekronos** [comment]
Aha, you need to backport this code then to 0.46. I think replacing `AsNumber()` with `AsInteger()` should do the trick.

**Comment by nekronos** [comment]
Apply this patch: 
```patch
diff --git a/NativeControls/DatePicker.ScriptClass.uno b/NativeControls/DatePicker.ScriptClass.uno
index 112f1ce..a1e0096 100644
--- a/NativeControls/DatePicker.ScriptClass.uno
+++ b/NativeControls/DatePicker.ScriptClass.uno
@@ -107,9 +107,9 @@ namespace Native

                public static LocalDate FromJSON(this JsonReader json)
                {
-                       var year = (int)json["year"].AsNumber();
-                       var month = (int)json["month"].AsNumber();
-                       var day = (int)json["day"].AsNumber();
+                       var year = (int)json["year"].AsInteger();
+                       var month = (int)json["month"].AsInteger();
+                       var day = (int)json["day"].AsInteger();
                        return new LocalDate(year, month, day);
                }

diff --git a/NativeControls/TimePicker.ScriptClass.uno b/NativeControls/TimePicker.ScriptClass.uno
index cb72ae6..2cafd33 100644
--- a/NativeControls/TimePicker.ScriptClass.uno
+++ b/NativeControls/TimePicker.ScriptClass.uno
@@ -81,8 +81,8 @@ namespace Native

                static LocalTime FromJSON(JsonReader json)
                {
-                       var hour = (int)json["hour"].AsNumber();
-                       var minute = (int)json["minute"].AsNumber();
+                       var hour = (int)json["hour"].AsInteger();
+                       var minute = (int)json["minute"].AsInteger();
                        return new LocalTime(hour, minute);
                }
        }
```

**Comment by JohannesaBrahms** [comment]
K, did that. Now the getter and setter methods get confused.

..\NativeControls\DatePicker.ScriptClass.uno(22.27): E4018: No suitable method found to override
..\NativeControls\DatePicker.ScriptClass.uno(29.25): E4018: No suitable method found to override
..\NativeControls\TimePicker.ScriptClass.uno(22.27): E4018: No suitable method found to override
..\NativeControls\TimePicker.ScriptClass.uno(29.25): E4018: No suitable method found to override

**Comment by nekronos** [comment]
Ah right! Here's the full patch:

```patch
diff --git a/NativeControls/DatePicker.ScriptClass.uno b/NativeControls/DatePicker.ScriptClass.uno
index 112f1ce..1c51fb4 100644
--- a/NativeControls/DatePicker.ScriptClass.uno
+++ b/NativeControls/DatePicker.ScriptClass.uno
@@ -19,14 +19,14 @@ namespace Native
 			readonly DatePickerBase _dp;
 			public override PropertyObject Object { get { return _dp; } }
 			public override bool SupportsOriginSetter { get { return false; } }
-			public override string Get(PropertyObject obj)
+			public override string Get()
 			{
 				LocalDate date = ZonedDateTime.Now.Date;
 				lock(_dp)
 					date = _dp._out;
 				return date.ToJSON();
 			}
-			public override void Set(PropertyObject obj, string value, IPropertyListener origin)
+			public override void Set(string value, IPropertyListener origin)
 			{
 				var date = JsonReader.Parse(value).FromJSON();
 				lock(_dp)
@@ -107,9 +107,9 @@ namespace Native
 
 		public static LocalDate FromJSON(this JsonReader json)
 		{
-			var year = (int)json["year"].AsNumber();
-			var month = (int)json["month"].AsNumber();
-			var day = (int)json["day"].AsNumber();
+			var year = json["year"].AsInteger();
+			var month = json["month"].AsInteger();
+			var day = json["day"].AsInteger();
 			return new LocalDate(year, month, day);
 		}
 
diff --git a/NativeControls/TimePicker.ScriptClass.uno b/NativeControls/TimePicker.ScriptClass.uno
index cb72ae6..d29bd75 100644
--- a/NativeControls/TimePicker.ScriptClass.uno
+++ b/NativeControls/TimePicker.ScriptClass.uno
@@ -19,14 +19,14 @@ namespace Native
 			readonly TimePickerBase _tp;
 			public override PropertyObject Object { get { return _tp; } }
 			public override bool SupportsOriginSetter { get { return false; } }
-			public override string Get(PropertyObject obj)
+			public override string Get()
 			{
 				LocalTime time = ZonedDateTime.Now.TimeOfDay;
 				lock (_tp)
 					time = _tp._out;
 				return ToJSON(time);
 			}
-			public override void Set(PropertyObject obj, string value, IPropertyListener origin)
+			public override void Set(string value, IPropertyListener origin)
 			{
 				var newTime = FromJSON(JsonReader.Parse(value));
 				lock (_tp)
@@ -81,8 +81,8 @@ namespace Native
 
 		static LocalTime FromJSON(JsonReader json)
 		{
-			var hour = (int)json["hour"].AsNumber();
-			var minute = (int)json["minute"].AsNumber();
+			var hour = json["hour"].AsInteger();
+			var minute = json["minute"].AsInteger();
 			return new LocalTime(hour, minute);
 		}
 	}
```

**Comment by JohannesaBrahms** [comment]
Hm, the issue is resolved, but had a complaint about build path too long (failed to crunch file..). Only when I moved it one level up, to the C root directory did I manage to build it. I wonder how it will work then it is added to the main project..

**Comment by nekronos** [comment]
Yeah, Gradle paths are just the worst
