### ISSUE TITLE
Android: how to use carousel for year instead of calendar

### ISSUE THREAD

**Issue by mitesh-mokko** [nekronos/FuseNativeControls#5]
We are using this package to provide date pickers in our app, and for our particular case the new default Android behavior of showing a calendar view for year selection is highly undesired.

How can we change this to use the spinners like it used to be?

**Comment by nekronos** [comment]
Please refer to the [`DatePicker`](https://developer.android.com/reference/android/widget/DatePicker.html) documentation for native specific issues
